pipeline:
    name: From Template
    identifier: From_Template
    template:
        templateRef: Sample_Pipeline_Template
        versionLabel: "1.0"
        templateInputs:
            stages:
                - stage:
                      identifier: Deploy_Service
                      type: Deployment
                      spec:
                          serviceConfig:
                              serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                      manifests:
                                          - manifest:
                                                identifier: Manifests
                                                type: K8sManifest
                                                spec:
                                                    store:
                                                        type: Github
                                                        spec:
                                                            connectorRef: <+input>
                                                            paths: <+input>
                                                            repoName: <+input>
                                                            branch: <+input>
                                      artifacts:
                                          primary:
                                              type: DockerRegistry
                                              spec:
                                                  tag: <+input>
                              serviceRef: <+input>
                          infrastructure:
                              environmentRef: <+input>
                              infrastructureDefinition:
                                  type: KubernetesDirect
                                  spec:
                                      connectorRef: <+input>
                                      namespace: <+input>
                - stage:
                      identifier: Deploy_Service_to_test
                      template:
                          templateInputs:
                              type: Deployment
                              spec:
                                  serviceConfig:
                                      serviceDefinition:
                                          type: Kubernetes
                                          spec:
                                              manifests:
                                                  - manifest:
                                                        identifier: template_manifest
                                                        type: HelmChart
                                                        spec:
                                                            store:
                                                                type: Github
                                                                spec:
                                                                    connectorRef: <+input>
                                                                    folderPath: <+input>
                                                                    repoName: <+input>
                                                                    branch: <+input>
                                                  - manifest:
                                                        identifier: template_valuess
                                                        type: Values
                                                        spec:
                                                            store:
                                                                type: Github
                                                                spec:
                                                                    connectorRef: <+input>
                                                                    paths: <+input>
                                                                    repoName: <+input>
                                                                    branch: <+input>
                                  infrastructure:
                                      environmentRef: <+input>
                                      infrastructureDefinition:
                                          type: KubernetesDirect
                                          spec:
                                              connectorRef: <+input>
                                              namespace: <+input>
    tags: {}
    projectIdentifier: Spring_Forward
    orgIdentifier: default
